name: class_manager
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.16.1
  provider: ^4.3.3
  fluttertoast: ^7.1.6
  flutter_svg: ^0.21.0-nullsafety.0
  flutter_icons: ^1.1.0
  cupertino_icons: ^0.1.3
  cloud_firestore: ^0.16.0
  firebase_auth: ^0.20.0+1
  email_validator: '^1.0.0'
  google_sign_in:
  uuid: ^3.0.1
  flutter_facebook_login:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.9.0"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
